QP/C: qk_sched.c File Reference
qk_sched.c File Reference
QK_sched_() implementation.
#include "qk_pkg.h"
Functions
void QK_sched_ (uint8_t p)
QK scheduler.
Detailed Description
QK_sched_() implementation.
Definition in file qk_sched.c.
Function Documentation
void QK_sched_ (uint8_t p)
QK scheduler.
Note:
QK_sched_() must be always called with interrupts locked. The scheduler might unlock the interrupts internally, but always returns with interrupts locked.
Definition at line 41 of file qk_sched.c.
References QActive_get_(), QF_active_, QF_gc(), QF_INT_DISABLE, QF_INT_ENABLE, QK_currPrio_, QK_TLS, QPSet64_findMax, QPSet8_findMax, QS_aoObj_, QS_BEGIN_NOCRIT_, QS_END_NOCRIT_, QS_QK_SCHEDULE, QS_TIME_, QS_U8_, and QActive::super.
Referenced by QK_mutexUnlock().